@port = 3000
@host = http://localhost:{{port}}


###
POST {{host}}/api/usuarios/registro
Content-Type: application/json

{
    "username": "Alfredo",
    "email":"Jalfredo1@gmail.com",
    "password":"12345",
    "rol": "profesor",
    "nombre": "alfredo",
    "apellidos":"moreno",
    "fecha_nacimiento":"2000/03/02",
    "genero": "m" ,
    "telefono": "61771711"
}

###
GET {{host}}/api/usuarios/registro

###
POST {{host}}/api/usuarios/login
Content-Type: application/json

{
    "email": "Jalfredo1@gmail.com",
    "password": "12345"
}

###
POST {{host}}/api/cursos/nuevo
Content-Type: application/json

{
    "nombre": "Desarrollo personal",
    "horas": "140",
    "categoria": "Bienestar personal"
}

###
PUT {{host}}/api/cursos/editar
Content-Type: application/json

{
    "nombre": "Consitucion",
    "horas": "140",
    "categoria": "Bienestar personal"
}
###
GET {{host}}/api/cursos/curso

###
DELETE {{host}}/api/cursos/borrar

###
POST {{host}}/api/profesores/nuevo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sIjoicHJvZmVzb3IiLCJpYXQiOjE3MTMyNjA5NzJ9.arhMNeBIg3TqZHN6Ce95pOPzYA6OIgjEkepynqLKQsA
Content-Type: application/json

{
    "experiencia": 5
}

###
PUT {{host}}/api/profesores/editar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sIjoiYWx1bW5vIiwiaWF0IjoxNzEzMTg5OTU5fQ.JSu_7aoHItfMXUqyJcaMM_kqOvw1PRU-eVPOpJY29yQ
Content-Type: application/json

{
    "experiencia": 10,
    "username": "pepi", 
    "email": "pei@gmail.com", 
    "password": "00000", 
    "rol": "profesor", 
    "nombre": "pepita", 
    "apellidos": "grilla", 
    "fecha_nacimiento": "1979/03/01", 
    "genero": "m", 
    "telefono": "369363636"
}

###
DELETE {{host}}/api/profesores/borrar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sIjoiYWx1bW5vIiwiaWF0IjoxNzEzMTg5OTU5fQ.JSu_7aoHItfMXUqyJcaMM_kqOvw1PRU-eVPOpJY29yQ


### 
GET {{host}}/api/profesores/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sIjoicHJvZmVzb3IiLCJpYXQiOjE3MTMyNTQyNzh9.PPif7dxctw-qyRO9lMavdur8La97HmvFYGCmmtfAfeU


###
POST {{host}}/api/alumnos/nuevo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sIjoicHJvZmVzb3IiLCJpYXQiOjE3MTMyNTU2NjN9.5SyPJsLaLxOmRi0eJmJ4S1vPrWukGi4kY4jnT7TQAuY